### ISSUE TITLE
Вынести логику маршрутизации

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#1]
Лучше локализовать логику, которая отвечает за делегирование обработки запроса до определенной функции. Это сразу сделает архитектуру приложения более явной. Каждый обработчик сделать отдельной функцией с определенным контрактом (который ты сам можешь сформулировать). И потом где-нибудь в логике инициации уже прописать какой урл и какой метод ведут до какого обработчика.

**Comment by mrRomanovsky** [comment]
Исправления внесены и находятся в ветке master.
