### ISSUE TITLE
isSimpleGet должен быть рекурсивен

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#10]
Сейчас ты проверяешь только первый параметр

**Comment by mrRomanovsky** [comment]
Не совсем понял, что именно нужно сделать рекурсивным: сейчас там происходят только сопоставления с образцом, которые выглядят так: 
`
isSimpleGet :: Query -> Bool
isSimpleGet [] = True
isSimpleGet (("page", p):qs) = True
isSimpleGet (("sort_by", sB):qs) = True
isSimpleGet _ = False
`

**Comment by Znack** [comment]
А у тебя же page может быть не первым аргументом, а вторым — после какого-нибудь аргумента фильтрации. Или наоборот — после аргумента page могут быть аргументы фильтрации и тд. Вообще название Simple не говорит о том, что же ты тут конкретно проверяешь, хотелось бы более семантичную версию :)

**Comment by mrRomanovsky** [comment]
Идея была в том, что сначала должна быть фильтрация, а потом уже остальные параметры. Поэтому, если начинается со страницы или сортировки, фильтровать будет не нужно. Возможно, название предиката не совсем удачное выбрал - изменю его.

**Comment by Znack** [comment]
Не-не, ты не можешь заставить использовать твое API таким образом. Пользователи REST API должны иметь возможность в любом порядке GET-параметры передавать :)

**Comment by mrRomanovsky** [comment]
А может ли одновременно быть фильтрация и сортировка?

**Comment by Znack** [comment]
Конечно, фильтрация, пагинация и сортировка (которая вроде бы необязательна) могут быть в произвольном наличии и порядке

**Comment by Znack** [comment]
> А несколько фильтров сразу может быть? Имею в виду, одновременно и по автору и по наличию тегов, например.

По хорошему да, но думаю, что категорически мы этого требовать не будем

**Comment by mrRomanovsky** [comment]
Сортировка не обязательна? Можно было её не делать?

**Comment by mrRomanovsky** [comment]
Сортировка не обязательна?

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/f16460c58a81c56c06c17e5c14528368e489966e
