### ISSUE TITLE
Вместо одинарного do-экшена и последующего return лучше использовать fmap

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#12]
```
do
  x <- someFunc a b c
  return $ f x
``` 
— такой код практически всегда легко трансформируется в:
```
f <$> someFunc a b c
```

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/50c83063c1a99f8d54e5764fc96f0c2a20a671bd

**Comment by Znack** [comment]
А у тебя hlint точно подключен, он обычно на эту тему ругается?

**Comment by mrRomanovsky** [comment]
В vscode в качестве расширения стоит. Он вроде бы подсвечивает места, где можно что-то улучшить - не знаю, что здесь пошло не так -  может, это я не заметил.
