### ISSUE TITLE
Сделать отдельный конструктор для несуществующего айди

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#13]
Лучше использовать отдельный конструктор для айдишников, которые еще не иницииарованы базой, использование `-1` — это боль, которую лучше оставить в C :)

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/5582dd634174cabeb06159bb4f6afca6834c6159

**Comment by Znack** [comment]
Кстати ты в коммите можешь указывать `closes #13` — тогда ишью будет автоматом закрываться при коммите и тут в ишью будет автоматом ссылка на коммит создаваться
