### ISSUE TITLE
Уровни логов не должны пересекаться с namespace

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#17]
При логировании приложений часто используются уровни логов и неймспейсы — это вещи ортогональные. То есть каждый лог и уровень имеет, и неймспейс. Чаще всего причем вещи эти вообще никак не связаны. Так что уровни лучше сделай уровней debug, info, warning, error. А requests — это по сути про то, какой модуль логирует, это неймспейс. Его можешь оставить (но тогда логично на всае остальные части системы тоже сделать логи, на бд, на инфраструктурную часть и тд), а можешь выпилить просто

**Comment by mrRomanovsky** [comment]
А чем должны отличаться уровни warning и error?

**Comment by Znack** [comment]
Можно дефолтные значения так логировать, например :) Вот пара статей про то, какие уровни чем отличаются:
https://stackoverflow.com/questions/7839565/logging-levels-logback-rule-of-thumb-to-assign-log-levels
https://blog.scalyr.com/2017/12/logging-levels/
