### ISSUE TITLE
Разделить приложение на функциональные модули, а не по слоям.

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#2]
Объединять лучше всегда не по слоям, а по семантике. То есть не делить приложение на обрабоичики Get и Post, а поделить лучше по смыслу: на User, Author, Post и тд, в каждом из которых уже будут и Get, и Post для юзера, в другом и Get, и Post для автора и тд. Так будет гораздо легче масштабировать сервер новыми фичами, плюс будет легче разобраться с арзхитектурой новичку, так как можно не изучать все фичи, а только те, что нужны для задачи. При текущей же архитектуре, чтобы добавить, например, модерирование статей, придется по всему проекту везде понемногу написать код :)

**Comment by mrRomanovsky** [comment]
Исправления внесены и находятся в ветке master.
