### ISSUE TITLE
Вынесение переиспользуемых мелких частей кода в функции

### ISSUE THREAD

**Issue by NikitaRzm** [mrRomanovsky/news-server#22]
Очень полезно в угоду читаемости и локальному переиспользованию выносить общий код в функции. Плюс потом вероятно он понадобится еще в паре мест и будет резон переиспользованию его в общий модуль - но это бывает реже при локальном обобщении.

1. Вот тут
https://github.com/mrRomanovsky/news-server/blob/master/src/Blog/Config/Config.hs#L22
fromMaybe {message} <$> lookupEnv {var_name} - можно вынести в локальную функцию :)
Не критично, но полезно, код станет проще читаться, обращай на это внимание :)

2. В Comment.hs и Draft.hs часть функций написана с использованием функций, обобщающих определенные действия над моделями, типа draftModelAction, есть ли какие-то проблемы, чтобы использовать их в других местах? В deleteDraft функции, например hlint говорит уменьшить дублирование :) Вопрос не в наличии хелперов - а проблематичности, почему не использовано везде? :)

**Comment by mrRomanovsky** [comment]
Функции вроде draftModelAction я добавил именно для драфтов - там для них иногда нужно отдельно автора искать и в самом драфте его изменять - я с остальными сущностями такого не делаю, поэтому решил не обобщать :)

**Comment by mrRomanovsky** [comment]
То, что hlint предлагает, исправлю в 23-м ишью, чтобы по кускам не разбивать.

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/3531a3513be1899608c8f0f881a33373c8eb42af
