### ISSUE TITLE
Подключить конфиг, чтобы там хранить все изменяемые параметры приложения

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#5]
Убрать хардкодинг приложений, типа имени лог файла и креденшиалов для базы данных. Это все должно конфигурироваться в одном выделенном месте. Также по требованиям к задаче там должен быть текущий минимальный уровень логирования, ниже которого все должно глушиться. Ну и порт либо туда вынести, либо аргументами строки принимать.

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/9632f698a58a245318f518b5522cff0af6786284
