### ISSUE TITLE
Оставить в app/Main самый минимум

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#6]
Это исполняемый файл, который по идее никуда больше нельзя импортивать — в идеале поэтому туда вообще самый минимум кода убирать, который точно никогда нигде не будет переиспользоваться. Сейчас там лежит много кода, который мог бы в будущем потенциально импортироваться в других местах, так что лучше все вынести в `src`.

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/fcfc94474523c311fd294148672c5959ed976574
