### ISSUE TITLE
Использовать модульную систему

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#7]
Сейчас у тебя глобальный неймспейс для всего проекта — это не очень удобно (и практически нигде в хаскельных библиотеках не используется). А используется подход, который гарантирует модульность имен: неймспейсы, когда имя модуля пишется через точку, например, `Network.HTTP.Types`.

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/f68ce731c36d4776990482b3da62220cabeb1758
