### ISSUE TITLE
Переименовать requests в handlers

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#8]
Не совсем корректно называть обработчики запросами, потому что там у тебя лежит бизнес-логика, которая обрабатывает запросы, а не создает их :)
Модули будут, соотвественно, например, `Blog.Handlers.Author` — обрати внимание, что по хорошему в начале еще отдельно неймспейс Blog добавляется

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/9e2bbddf73cb9be2dc21cc5f121b31c706fe38bc
