### ISSUE TITLE
Вынести из DbRequests функционал по конкретным сущностям

### ISSUE THREAD

**Issue by Znack** [mrRomanovsky/news-server#9]
Всегда лучше разделять код, который в целом решает задачу какого-то слоя в твоем приложении, от модулей. У тебя в DbRequests, который вроде бы максимально абстрактный модуль, не привязанный ни к какой функицональности конкретной, вдруг лежит код, который знает про конкретную сущность — author. Ответственность всегда лучше максимально разделять, тогда проще код изучать, проще код изменять и проще по проекту искать. Советую частный случай по работе с автором вынести куда-нибудь в специфичный для автора код, плюс у тебя внезапно DbRequests знает про то, что есть таблица `categories`, там пока что хватит немного более общего решения, при котором все таблицы, заканчивающиеся на `ies` заменять на `y` и получать что-то вроде `category_id`, как бы ты для остальных таких случаев получил.

**Comment by Znack** [comment]
И не надо будет потом в `Router.hs` импортировать `DbRequests` 😆

**Comment by mrRomanovsky** [comment]
https://github.com/mrRomanovsky/news-server/commit/d5b938f58e6fe4f03211071eb942cf3c2387f760
